---
# ensure docker module is present on Ansible host
- name: Ensure Docker Module for Python is present on Ansible host
  hosts: localhost
  become: yes
  tasks:

  - name: Ensure python3-pip package is installed
    apt:
      update_cache: yes
      pkg:
      - python3-pip
      state: present
    register: local_apt_status
    until: local_apt_status is success
    delay: 6
    retries: 10

  - name: install docker pip
    pip:
      state: present
      name: docker
      executable: /usr/bin/pip3

# build server setup
- name: install maven
  hosts: build
  become: yes

  tasks:
  - name: Ensure default-jdk/maven/git packages are installed
    apt:
      update_cache: yes
      pkg:
      - default-jdk
      - maven
      - git
      - awscli
      - docker.io
      - docker-compose
      state: present
    register: build_apt_status
    until: build_apt_status is success
    delay: 6
    retries: 10

# building war
- name: build war
  hosts: build
  become: yes

  tasks:
  - name: clone files from Git repository
    git:
      repo: 'https://github.com/Avasekho/app42_postgres_clone.git'
      dest: /tmp/app42

  - name: package war
    shell:
      chdir: /tmp/app42
      cmd: mvn package

# tasks build and push docker
  - name: sync dockerfile
    synchronize:
      mode: push
      src: './Dockerfile'
      dest: '/tmp/app42/target/Dockerfile'

  - name: Retrieve AWS authentication token
    shell: "aws ecr get-login --no-include-email --region us-east-1"
    register: ECR_token_output_b

  - name: Docker login
    shell: "{{ ECR_token_output_b.stdout }}"

  - name: Build and push Tomcat container
    docker_image:
      build:
        path: /tmp/app42/target/
        pull: yes
        args:
          listen_port: 8080
      name: 373000727222.dkr.ecr.us-east-1.amazonaws.com/app_deployment
      tag: v1
      push: yes
      source: build

# build server setup
- name: install docker
  hosts: prod
  become: yes

  tasks:
  - name: Ensure docker packages are installed
    apt:
      update_cache: yes
      pkg:
      - awscli
      - docker.io
      - docker-compose
      state: present
    register: prod_apt_status
    until: prod_apt_status is success
    delay: 6
    retries: 10

# pull and start docker container
- name: pull docker container
  hosts: prod
  become: yes

  tasks:
  - name: Retrieve AWS authentication token
    shell: "aws ecr get-login --no-include-email --region us-east-1"
    register: ECR_token_output_p

  - name: Docker login
    shell: "{{ ECR_token_output_p.stdout }}"

  - name: install tomcat container
    docker_compose:
      project_name: webapp42
      definition:
        version: '2'
        services:
          tomcat:
            image: 373000727222.dkr.ecr.us-east-1.amazonaws.com/app_deployment:v1
            ports: 
              - "8080:8080"
          db:
            image: postgres:12
            restart: always
            ports: 
              - "5432:5432"
            environment:
              POSTGRES_USER: dbadmin
              POSTGRES_PASSWORD: dbpassword
              POSTGRES_DB: webappdb